---
title: "Prep assemblies"
author: "Tamás Stirling"
output: html_document
---

## Prepare "assembles.tsv" for snippy

```{r}
rm(list=ls())
load("aci_all.rda")
```


```{r}
index <- which(aci$assembly %in% c(
  "Aci128_Belgrade8",
  "Aci134",
  "Aci139",
  "GCA_016481385.1",
  "GCA_016489425.1"
))
aci_selection <- rbind(
  aci[which(aci$continent == "europe"),],
  aci[which(include_firsts == TRUE),],
  aci_to_sample[index,]
)
#table(aci_selection$continent)
```

```{r eval}
write.table(aci_selection,
            file = "assemblies.tsv",
            row.names = FALSE,
            quote = FALSE,
            sep = "\t")
```

## Prepare "dates.tsv" for treedater and TreeTime

```{r}
load("srr.rda")
load("assembly_meta.rda")
load("biosample_meta.rda")
load("aci_results_with_metadata.rda")
ncbi <- dplyr::left_join(srr, biosample_meta, by = "sra")
ncbi <- dplyr::left_join(ncbi, assembly_meta, by = "biosample")
ncbi <- dplyr::left_join(ncbi, aci)
ncbi <- ncbi[,-which(names(ncbi) == "assembly")]
ncbi <- dplyr::rename(ncbi, assembly = srr)
index <- which(names(ncbi) %in% c(names(aci_selection), "geographic_location"))
ncbi <- ncbi[,index]
aci <- dplyr::bind_rows(aci_selection, ncbi)
```

```{r}
date_middle <- function(dates){
  foo <- function(x){
    if(is.na(x)) return(NA)
    date_elements <- strsplit(x, split = "-")[[1]]
    year <- date_elements[1]
    if (length(date_elements) == 1){
      date <- paste(year, "06","15", sep = "-")
    }
    if (length(date_elements) == 2){
      month <- date_elements[2]
      date <- paste(year, month, "15", sep = "-")
    }
    if (length(date_elements) == 3){
      date <- x
    }
    return(date)
  }
  out <- as.Date(sapply(dates, foo))
  return(out)
}
aci$collection_day <- date_middle(aci$collection_date)
```

```{r}
treetime <- data.frame(
  name = aci$assembly,
  date = aci$collection_day
)

write.table(treetime,
            file = "dates.tsv",
            sep = "\t",
            row.names = FALSE,
            quote = FALSE)
```

## Prepare "treemeta.rda" for ggtree

```{r}
save(aci, file = "treemeta.rda")

write.table(aci,
            file = "treemeta.tsv",
            sep = "\t",
            row.names = FALSE,
            quote = FALSE)
```



