#' Export a tables
#' 
#' This is a convenience function for exporting tables generated by any of the
#' processes.
#' @param data a table, e.g. data frame or matrix
#' @param file path to the output file
write_tsv <- function(data, file) {
  if (!grepl("tsv$", file)) {
    stop("Output file must be a .tsv file.")
  }
  write.table(
    data,
    file = file,
    sep = "\t",
    row.names = FALSE,
    quote = FALSE,
    na = ""
  )
}